#ifndef STATUS_H
#define STATUS_H
enum class Status{
    OK,
    FILE_OPEN_WRONG,
    COMPILE_ERROR,
    CANT_FIND_PYTHON,
    UNKNOWN_SYSTEM,
    NETWORK_ERROR,
    DEEPSEEK_ERROR,
    FILE_DELETE_ERROR,
    PROCESS_ERROR
};

#endif // STATUS_H
